### ISSUE TITLE
Server under heavy load?

### ISSUE THREAD

**Issue by skorokithakis** [Pushjet/Pushjet-Server-Api#15]
The server is taking from multiple seconds up to a minute to send pushes, what is the problem? Is there anything we can do to help?

**Comment by skorokithakis** [comment]
Ah, it's not load. Calls just seem to time out under IPv6. Is nginx not listening on the IPv6 interfaces?

**Comment by skorokithakis** [comment]
Actually, the server doesn't even respond to ping over IPv6. Is the hostname correct?

**Comment by Mechazawa** [comment]
I had ipv6 disabled for quite a while due to issues with malicious hosts. Currently updating my DNS records and adding my ipv6 range to my server.

**Comment by skorokithakis** [comment]
Amazing, thank you! I'll try again soon.

**Comment by Mechazawa** [comment]
Is it working? My home connection does not support IPv6 at the moment.

**Comment by skorokithakis** [comment]
Yes it does, thanks!
