### ISSUE TITLE
Often getting 502 Bad Gateway from official server

### ISSUE THREAD

**Issue by relrod** [Pushjet/Pushjet-Server-Api#29]
When trying to use the "official" server, it seems every few messages, I get a 502 bad gateway error and my message doesn't get delievered...

**Comment by skorokithakis** [comment]
Same here, this has been happening for a while.

**Comment by zivester** [comment]
Haven't gotten a push notification myself since Sept. 22nd, may try to reach out to the developer directly :-/

**Comment by skorokithakis** [comment]
Same here :/ I switched to pushover because of this, which is a shame as I would have definitely given money to Pushjet instead, if it meant that it'd keep the servers up.

**Comment by zivester** [comment]
I believe they just restarted the server, I started getting alerts again. Thanks @Mechazawa

**Comment by Mechazawa** [comment]
Yeah sorry about that, gunicorn crashed and for some reason I didn't get an SMS notification. 
Life's been really hectic for me but I'm still working on a Pushjet rewrite in my spare time.

**Comment by AvnerCohen** [comment]
Getting 500 consistently. Is the server down for good?

Any way to check the api status ?

**Comment by yatsek** [comment]
Getting the same as @AvnerCohen.

**Comment by linusg** [comment]
Same here!

**Comment by zivester** [comment]
@Mechazawa any idea what's going on with the server?  Also not able to send push notifications for ~2 weeks now.

**Comment by Mechazawa** [comment]
Sorry about that, I don't have the time to maintain this project anymore and it kinda slipped through the cracks. I've fixed the issue. It had to do with a misconfigured server with some outdated packages that were causing issues. 

It should be fixed. I'll close this issue, please remake one when this happens again.

**Comment by linusg** [comment]
Will it be shut down or are you looking for someone to maintain the service and code? I am able to run it on a custom server, but it's a great project and not everyone can deploy their own instance...

**Comment by Mechazawa** [comment]
>Will it be shut down or are you looking for someone to maintain the service and code?

If someone is willing to step up and maintain Pushjet then I'm open to that.
