### ISSUE TITLE
SSL Cert Expired https://api.pushjet.io

### ISSUE THREAD

**Issue by zivester** [Pushjet/Pushjet-Server-Api#32]
Seems that the SSL cert is invalid today for https://api.pushjet.io/

@Mechazawa is this an easy fix?

**Comment by Mechazawa** [comment]
Might have borked that up while I was migrating my server.

**Comment by Mechazawa** [comment]
Should be fixed now. I accidentally used an older certificate most likely. I just generated a new one and it should be fixed.
