### ISSUE TITLE
Cannot create service

### ISSUE THREAD

**Issue by Dissimilis** [Pushjet/Pushjet-Server-Api#34]
Every time error is returned when creating service:
```
{
  "error": {
    "id": 7,
    "message": "Missing argument name"
  }
}
```
Whats wrong? Tried everything: headers, no headers, different content types, etc..

![pushjet](https://user-images.githubusercontent.com/7642759/35475131-aefe6cac-03a1-11e8-8f5b-c16817636e84.jpg)

**Comment by Mechazawa** [comment]
Pushjet uses classic http parameters, not json, for it's input.

For example:
``` 
~> curl https://api.pushjet.io/service -d name=foobar
{
  "service": {
    "created": 1517101408, 
    "icon": "", 
    "name": "foobar", 
    "public": "e8f9-2a0add-17fe891f002d-750ca-d89c64cbc", 
    "secret": "e18349e6060b2aa258952b4d37086c1a"
  }
}
```
