### ISSUE TITLE
Some messages do not get delivered

### ISSUE THREAD

**Issue by ftruzzi** [Pushjet/Pushjet-Server-Api#9]
Hello,

thank you for this software, it really suits my needs. However, I was doing some tests today and found out that not all the pushed messages get delivered to the subscribed devices. I usually run the server on an Amazon EC2 instance but the problem appears on a fresh virtual machine as well.

Here's a screenshot: https://i.imgur.com/6hEkIal.png 

The top right terminal (client.py) should show numbers from 0 to 9 but only shows 6 and 8.

If I send all 10 numbers and then subscribe to the service everything works fine, but if sending and receiving at the same time, some messages get lost. The SQL 'message' table is empty as well.

Maybe I should mention that I run the server from the console by typing ./application.py (and it shows all the 10 POST requests). Am I missing some steps? Do I need to install pushjet-server-broker? Or maybe it's a bug in my code? 

Thanks,
Francesco

**Comment by Mechazawa** [comment]
~~I _think_ this is a race condition. I'll write a quick fix for it~~

It's not

**Comment by Mechazawa** [comment]
> The SQL 'message' table is empty as well.

Messages are deleted after delivery to all subscribers.

**Comment by Mechazawa** [comment]
The issue was that the `TIMESTAMP` field in MySQL does not store miliseconds and thus the system often shought that you already read a message when the timestamps overlapped.

It has been fixed using 5075634b94c11c6c82e1a51f9c3503cca682bc4f...67097bf668b88e788a0b0bffc41c9bb9a62398a2

**Comment by ftruzzi** [comment]
Great! Thanks for the very quick fix. I hope I can contribute to the software someday :)

EDIT: Tested and works fine. Just for reference, is someone needs to keep their old database, they need to run the following mysql commands to add the new column with no null values:

`ALTER TABLE subscription ADD last_read INT(10);`
`UPDATE subscription SET last_read = 0 WHERE id > 0;`
